# Generated by Django 4.2.4 on 2023-11-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositoptions',
            name='fin_prdt_cd',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='savingoptions',
            name='fin_prdt_cd',
            field=models.TextField(null=True),
        ),
    ]
